name: Build PR Documentation

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@test-build-pr-outside-container
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: huggingface_hub
      languages: cn de fr en hi ko
      custom_container: "" # no need for transformer's docker image
